name: Run Tests

on: [push, pull_request]

jobs:
  node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci --ignore-scripts
      - name: Run tests
        run: npm test
        env:
          CI: true
  deno:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deno-version: [1.31.x, 1.x]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}  
      - name: Run tests
        run: deno test test/
        env:
          CI: true